enum AtomCode {
    ID = 0,
    CONST = 1,
    KEYWORD_INT = 2, KEYWORD_FLOAT = 3, KEYWORD_STRING = 4,
    KEYWORD_IF = 5, KEYWORD_ELSE = 6, KEYWORD_WHILE = 7, KEYWORD_RETURN = 8,
    KEYWORD_CIN = 10, KEYWORD_COUT = 11,
    OP_PLUS = 12, OP_MINUS = 13, OP_MULT = 14, OP_DIV = 15, OP_MOD = 16,
    OP_ASSIGN = 17, OP_EQUAL = 18, OP_LESS = 19, OP_LESS_EQ = 20,
    OP_GREATER = 21, OP_GREATER_EQ = 22, OP_NOT_EQ = 23,
    OP_AND = 24, OP_OR = 25,
    OP_READ = 26, OP_WRITE = 27,
    DELIM_LPAREN = 28, DELIM_RPAREN = 29, DELIM_LBRACE = 30, DELIM_RBRACE = 31,
    DELIM_SEMICOLON = 32, DELIM_COMMA = 33,
    DIR_INCLUDE = 34, DIR_USING = 35,

    KEYWORD_DO = 36, KEYWORD_DOEND = 37
};
